name: IGChat
options:
  bundleIdPrefix: com.patternalcreation
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  IGChat:
    type: application
    platform: iOS
    sources:
      - App
    settings:
      base:
        PRODUCT_NAME: IGChat
        PRODUCT_BUNDLE_IDENTIFIER: com.patternalcreation.igchat
        MARKETING_VERSION: "1.28.5"
        CURRENT_PROJECT_VERSION: "63"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: IG Chat
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_BITCODE: NO
        ARCHS: arm64
        ONLY_ACTIVE_ARCH: NO
