name: k3-calculator

options:
  bundleIdPrefix: com.k3
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  k3-calculator:
    type: application
    platform: iOS
    sources:
      - Calculator
    settings:
      base:
        PRODUCT_NAME: k3-calculator
        PRODUCT_BUNDLE_IDENTIFIER: com.k3.calculator
        MARKETING_VERSION: "1.2.0"
        CURRENT_PROJECT_VERSION: "3"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: Calculator
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_BITCODE: NO
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        ONLY_ACTIVE_ARCH: NO
        ARCHS: arm64
